# Generated by Django 3.0.6 on 2020-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='requirement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Требования'),
        ),
    ]
